#pragma once

enum class Notification
{
	VELOCITY_CHANGED,
	ANGULAR_VELOCITY_CHANGED,
	POSITION_CHANGED,
	ORIENTATION_CHANGED,
	SPEED_CHANGED,
	PREDICTION_TIME_CHANGED,
	WANDER_RATE_CHANGED,
	SUBJECT_DISTROYED,
};
